WebApplication17/WebApplication17/Controllers/SamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.OleDb;
using System.Data;
using System.IO;
using System.Configuration;

namespace WebApplication17.Views
{
    public class SamController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {
                string path = Server.MapPath("~/Content/uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string filePath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filePath);
                string conString = string.Empty;
                switch (extension)
                {
                    case ".xls":
                        conString = ConfigurationManager.ConnectionStrings["Excel03ConString"].ConnectionString;
                        break;
                    case ".xlsx":
                        conString = ConfigurationManager.ConnectionStrings["Excel07ConString"].ConnectionString;
                        break;
                }
                conString = string.Format(conString, filePath);
                using (OleDbConnection connExcel = new OleDbConnection(conString))
                {
                    using (OleDbCommand cmdExcel = new OleDbCommand())
                    {
                        using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                        {
                            DataTable dt = new DataTable();
                            cmdExcel.Connection = connExcel;
                            connExcel.Open();
                            DataTable dtExcelSchema;
                            dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                            string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                            connExcel.Close();
                            connExcel.Open();
                            cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                            odaExcel.SelectCommand = cmdExcel;
                            odaExcel.Fill(dt);
                            connExcel.Close();
                            ViewBag.Data = dt;
                        }
                    }
                }
            }
            return View();
        }
    }
}

WebApplication17/WebApplication17/Views/Sam/DeleteModal.cshtml
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">WARNING</h4>
            </div>
            <div class="modal-body">
                <label>Are you sure ?</label>
            </div>
            <div class="modal-footer">
                <button type="button" id="yesbut" class="btn btn-success" data-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">No</button>
            </div>
        </div>

    </div>
</div>

WebApplication17/WebApplication17/Views/Sam/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@*<!DOCTYPE html>*@

@*<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>*@
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>*@
@*</head>
<body>*@
<div class="container-fluid">
    <label class="header">Quick Edit</label>
    <div class="row">
            @using (Html.BeginForm("Index", "Sam", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="col-md-6" style="color:white"><input type="file" name="postedFile"></div>
                <div class="col-md-6" style="padding-left:30px"><input type="submit" class="btn btn-default" value="Show" id="show"></div>
            }
    </div>
    <div id="instr" style="color:white;border:groove;margin-top:10px">
        <label style="font-size:24px;padding-left:10px">Instructions</label>
        <ul>
            <li>Click "Choose file" button and choose your file to display</li>
            <li>After your table is displayed,Edit file according to your needs</li>
        </ul>
        <label style="padding-left:10px;font-weight:400">*Note: This table does not save data anywhere so it is advised to download the excel before switching pages</label>
    </div>
    <div class="row">
            @Html.Partial("TablePartial")
    </div>
</div>
@*</body>
</html>*@
<script>
    $(document).ready(function () {
        if ($("#tabs > tbody > tr").length != 0) {
            $("#instr").prop('hidden', true);
        }
    });
</script>